version: 1.0.{build}
image: Visual Studio 2017 Preview
configuration: Release
platform: Any CPU
before_build:
- cmd: >-
    appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

    nuget restore  Dynamic.Trader.sln
build:
  project: Dynamic.Trader.sln
  verbosity: minimal
after_build:
- cmd: >-
    7z a DynamicTrader.zip %APPVEYOR_BUILD_FOLDER%\Trader.Client\bin\release\net462\*.*

    appveyor PushArtifact DynamicTrader.zip
